#!/usr/bin/env bash
# Fails a pull request that changes addons/launcher/ without moving
# LauncherVersion.VERSION.
#
# VERSION is hand-maintained -- the sync stamps COMMIT, SYNCED_AT and SOURCE,
# and deliberately leaves VERSION alone, because it is the template's to declare.
# Hand-maintained meant nothing maintained it: it sat at 1.0.0 across four
# changes to addons/launcher/, one of which removed a public constant
# (UpdateService.REQUEST_TIMEOUT). Code written against "launcher 1.0.0" failed
# against "launcher 1.0.0".
#
# COMMIT answers "which revision" precisely once a game has synced. VERSION is
# the half meant to be readable by a human, and to survive being vendored by
# hand, where COMMIT stays "local" forever.
#
#   bash ci/check_launcher_version.sh <base-ref> [head-ref]
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

VERSION_FILE="addons/launcher/launcher_version.gd"
RECORD="addons/launcher/.launcher-sync.json"

BASE="${1:-}"
HEAD="${2:-HEAD}"

if [[ -z "$BASE" ]]; then
	echo "usage: bash ci/check_launcher_version.sh <base-ref> [head-ref]" >&2
	exit 2
fi

# Only the repository that OWNS the launcher can set its version.
#
# ci/ is synced into consuming games wholesale, so this script travels with it.
# In a game, addons/launcher/ changes only by sync -- and the sync writes COMMIT,
# never VERSION. Enforcing the rule there would fail every sync pull request,
# blocking the launcher update it exists to deliver, over a value the game has
# no business setting. The sync record is the distinction, and an intrinsic one:
# it exists only in a repository that pulled the launcher in from somewhere else,
# so this needs no hardcoded repository name and survives a fork of the template.
if [[ -f "$RECORD" ]]; then
	echo "This repository syncs its launcher from upstream; VERSION is upstream's to set."
	echo "Skipping the bump check."
	exit 0
fi

# Two refs are compared, so uncommitted work is invisible. In CI that is exactly
# right -- the pull request's changes are commits. Run by hand against a dirty
# tree it would pass by not looking, which is the same shape as the bug this
# check exists to prevent, so say so.
if [[ "$HEAD" == "HEAD" ]] && ! git diff --quiet -- addons/launcher/; then
	echo "note: addons/launcher/ has uncommitted changes. This compares commits and will not see them." >&2
fi

# Which files under addons/launcher/ this pull request touches.
#
# .uid sidecars are regenerated by the Godot editor and carry no behaviour, so a
# change confined to them is not a launcher change. They are excluded from the
# trigger, not from the diff: a .uid that moves alongside real edits is fine, it
# just cannot be the only thing that moved.
mapfile -t CHANGED < <(git diff --name-only "$BASE" "$HEAD" -- addons/launcher/ | grep -v '\.uid$' || true)

if (( ${#CHANGED[@]} == 0 )); then
	echo "No behavioural change under addons/launcher/; nothing to check."
	exit 0
fi

read_version() { # $1 = git ref
	git show "$1:$VERSION_FILE" 2>/dev/null \
		| sed -n 's/^const VERSION: String = "\(.*\)"$/\1/p' \
		| head -1
}

# Empty at base means the file did not exist there -- a launcher being added for
# the first time. Any VERSION at head differs from that, which is the right
# answer rather than a special case.
BASE_VERSION="$(read_version "$BASE")"
HEAD_VERSION="$(read_version "$HEAD")"

if [[ -z "$HEAD_VERSION" ]]; then
	echo "::error file=${VERSION_FILE}::Could not read VERSION from ${VERSION_FILE}. Expected a line of the form: const VERSION: String = \"x.y.z\""
	exit 1
fi

if [[ "$BASE_VERSION" != "$HEAD_VERSION" ]]; then
	echo "VERSION moved ${BASE_VERSION:-(absent)} -> ${HEAD_VERSION}. ${#CHANGED[@]} launcher file(s) changed."
	exit 0
fi

# Set by the workflow from a pull request label. Checked last, so the log still
# records what changed and which version stood still.
if [[ "${LAUNCHER_VERSION_EXEMPT:-}" == "true" ]]; then
	echo "::notice::addons/launcher/ changed with VERSION held at ${HEAD_VERSION}, by label."
	exit 0
fi

{
	echo "::error file=${VERSION_FILE},line=10::addons/launcher/ changed but LauncherVersion.VERSION is still ${HEAD_VERSION}. Bump it, or label the pull request 'no-launcher-bump'."
	echo
	echo "These launcher files changed:"
	printf '  %s\n' "${CHANGED[@]}"
	echo
	echo "VERSION is ${HEAD_VERSION} on both sides. Which component moves is a judgement:"
	echo "  MAJOR  a game's existing code stops compiling -- a removed or renamed const,"
	echo "         signal, or exported property, or a changed method signature"
	echo "  MINOR  new public surface that existing code does not have to care about"
	echo "  PATCH  a fix with no interface change"
	echo
	echo "If this genuinely does not warrant a bump -- a comment, a typo -- put the"
	echo "'no-launcher-bump' label on the pull request and re-run."
} >&2
exit 1
