#!/usr/bin/env python3
"""Extract the launcher's translatable strings into addons/launcher/launcher.pot.

Godot 4.7 cannot do this headlessly: there is no --export-pot, POTGenerator is not
exposed to script, and setting translations_pot_files does nothing outside the
editor. So the template ships a generated .pot and this script generates it --
which also means the extraction rule is written down here rather than being
whatever the editor happened to do.

The rule: the launcher's own player-facing strings reach a translator through a
tr() or tr_n() call in addons/launcher/**/*.gd. Nothing is read out of
launcher.tscn, deliberately -- the scene also holds strings the launcher does NOT
own (a game's title, its tagline) and placeholders overwritten at runtime, and no
rule based on reading .tscn could separate those from real launcher text without a
hand-maintained exception list that would quietly rot.

One launcher-owned string is deliberately left out: BuildInfo.display_version()'s
build stamp ("v%s · bin %d · content %d", "launcher %s"). It is diagnostic text
meant to be pasted into a bug report, and is easier to read untranslated.

Source is tokenised rather than scanned line by line, so a call split across
lines is found, a tr() in a comment or inside another string is not mistaken for
one, and both quote styles work. A tr() whose argument is not a literal cannot be
extracted; the script says so by name instead of skipping it quietly.

Output is byte-stable: no timestamps, entries sorted, so CI can regenerate and
diff to prove the committed file is current.
"""

from __future__ import annotations

import pathlib
import re
import sys

SOURCE_DIR = pathlib.Path("addons/launcher")
OUT = SOURCE_DIR / "launcher.pot"

PLACEHOLDER = re.compile("\x00(\\d+)\x00")
TR = re.compile(r"\btr\(\s*\x00(\d+)\x00\s*(?:,\s*\x00(\d+)\x00\s*)?\)")
TR_N = re.compile(r"\btr_n\(\s*\x00(\d+)\x00\s*,\s*\x00(\d+)\x00\s*,")
ANY_CALL = re.compile(r"\btr(?:_n)?\(")
SPECIFIER = re.compile(r"%(?:\d+\$)?[-+ 0#]*\d*(?:\.\d+)?[sdfxXoc]")

# "Language: " is present and empty on purpose. A .po copied from this template
# and left as-is is then loaded under no locale and translates nothing, which is
# the safe failure. Omitting the field entirely is not safe: Godot falls back to
# the project's own locale, so one unfilled catalogue would be served to every
# player, English included.
HEADER = '''# Translation template for the launcher's own screens.
#
# Generated by ci/make_pot.py from the tr() calls in addons/launcher/ --
# regenerate it with that script rather than editing this file.
#
# In YOUR copy (fr.po, de.po, …) you do edit the header: set Language: to the
# language code, and Plural-Forms: to that language's rule. Godot reads the
# locale from the Language: header, NOT from the filename -- a .po that leaves it
# empty translates nothing, and one that drops the line is served to every
# locale.
#
# Put your .po files OUTSIDE addons/launcher/ and OUTSIDE ci/ --
# res://locale/<lang>.po is the usual home. Both of those directories are
# replaced wholesale by ci/sync_launcher.sh, so a .po left inside either one is
# deleted on the next launcher sync. Register them in project.godot under
# internationalization/locale/translations, which is a game-owned file and
# survives the sync.
#
msgid ""
msgstr ""
"Language: \\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"
'''


def mask(text: str) -> tuple[str, list[str]]:
    """Blank comments and swap each string literal for a \\x00N\\x00 placeholder.

    Newlines are preserved so positions in the masked text still give the right
    line numbers.
    """
    literals: list[str] = []
    out: list[str] = []
    i, n = 0, len(text)
    while i < n:
        ch = text[i]
        if ch == "#":
            end = text.find("\n", i)
            end = n if end == -1 else end
            out.append(" " * (end - i))
            i = end
        elif ch in "\"'":
            if text[i : i + 3] in ('"""', "'''"):
                quote = text[i : i + 3]
                i += 3
                end = text.find(quote, i)
                end = n if end == -1 else end
                raw, i = text[i:end], min(end + 3, n)
            else:
                quote = ch
                i += 1
                buf: list[str] = []
                while i < n:
                    if text[i] == "\\":
                        buf.append(text[i : i + 2])
                        i += 2
                        continue
                    if text[i] == quote:
                        i += 1
                        break
                    if text[i] == "\n":
                        break
                    buf.append(text[i])
                    i += 1
                raw = "".join(buf)
            out.append(f"\x00{len(literals)}\x00" + "\n" * raw.count("\n"))
            literals.append(raw)
        else:
            out.append(ch)
            i += 1
    return "".join(out), literals


def line_of(masked: str, pos: int) -> int:
    return masked.count("\n", 0, pos) + 1


def collect() -> dict[tuple[str, str | None], dict]:
    entries: dict[tuple[str, str | None], dict] = {}
    problems: list[str] = []
    for path in sorted(SOURCE_DIR.rglob("*.gd")):
        masked, literals = mask(path.read_text(encoding="utf-8"))
        found: set[int] = set()
        for match in TR_N.finditer(masked):
            single, plural = literals[int(match.group(1))], literals[int(match.group(2))]
            entry = entries.setdefault((single, None), {"plural": None, "where": []})
            entry["plural"] = plural
            entry["where"].append(f"{path}:{line_of(masked, match.start())}")
            found.add(match.start())
        for match in TR.finditer(masked):
            msgid = literals[int(match.group(1))]
            context = literals[int(match.group(2))] if match.group(2) else None
            entry = entries.setdefault((msgid, context), {"plural": None, "where": []})
            entry["where"].append(f"{path}:{line_of(masked, match.start())}")
            found.add(match.start())
        # Every tr()/tr_n() in real code must have been one of the two above. One
        # that was not takes an argument this script cannot read -- said by name,
        # because silently skipping it is how a string goes missing from the
        # template and so is never offered to a translator.
        for match in ANY_CALL.finditer(masked):
            if match.start() in found:
                continue
            rest = masked[match.end() : match.end() + 40]
            if PLACEHOLDER.match(rest.lstrip()):
                problems.append(
                    f"{path}:{line_of(masked, match.start())}: tr() call this script "
                    f"cannot read -- check the argument list"
                )
            else:
                # tr(variable): intentional for a value supplied by the game, which
                # has no msgid to extract. LauncherConfig.resolved_tagline() is the
                # one in the launcher today.
                print(
                    f"note: {path}:{line_of(masked, match.start())}: "
                    f"tr() on a non-literal argument, nothing to extract",
                    file=sys.stderr,
                )
    if problems:
        for problem in problems:
            print(f"::error::{problem}", file=sys.stderr)
        sys.exit(1)
    return entries


def render(entries: dict[tuple[str, str | None], dict]) -> str:
    out = [HEADER]
    for msgid, context in sorted(entries, key=lambda k: (k[0], k[1] or "")):
        entry = entries[(msgid, context)]
        out.append("")
        for where in entry["where"]:
            out.append(f"#: {where}")
        if len(SPECIFIER.findall(msgid)) > 1:
            # Said explicitly because getting it wrong is a hard runtime error,
            # not a cosmetic one: "build %d · v%s" with the arguments swapped
            # raises "a number is required" and renders the raw format string.
            out.append("#. NOTE: more than one placeholder. To reorder them, use")
            out.append("#. indexed forms (%1$s, %2$d, …). Swapping a bare %s and %d")
            out.append("#. is a runtime error, not a typo.")
        if context is not None:
            out.append(f'msgctxt "{context}"')
        out.append(f'msgid "{msgid}"')
        if entry["plural"] is not None:
            out.append(f'msgid_plural "{entry["plural"]}"')
            out.append('msgstr[0] ""')
            out.append('msgstr[1] ""')
        else:
            out.append('msgstr ""')
    return "\n".join(out) + "\n"


def main() -> int:
    if not SOURCE_DIR.is_dir():
        sys.exit(f"run from the repository root: {SOURCE_DIR} not found")
    entries = collect()
    if not entries:
        sys.exit("no tr() or tr_n() calls found -- refusing to write an empty template")
    text = render(entries)
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"::error::{OUT} is out of date. Run: python3 ci/make_pot.py", file=sys.stderr)
            return 1
        print(f"{OUT} is up to date ({len(entries)} strings).")
        return 0
    OUT.write_text(text, encoding="utf-8")
    plurals = sum(1 for e in entries.values() if e["plural"] is not None)
    print(f"Wrote {OUT}: {len(entries)} strings ({plurals} with plural forms).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
