#!/usr/bin/env python3
"""Extract the launcher's translatable strings into addons/launcher/launcher.pot.

Godot 4.7 cannot do this headlessly: there is no --export-pot, POTGenerator is not
exposed to script, and setting translations_pot_files does nothing outside the
editor. So the template ships a generated .pot and this script is what generates
it -- which also means the extraction rule is written down here rather than being
whatever the editor happened to do.

The rule is simply: every string the launcher owns reaches the player through a
tr() or tr_n() call in addons/launcher/*.gd. Nothing is read out of launcher.tscn.
That is deliberate -- the scene also holds strings the launcher does NOT own (a
game's title, a tagline) and placeholders overwritten at runtime, and no rule
based on reading .tscn could tell those apart from real launcher text without a
hand-maintained exception list that would quietly rot. Every scene label the
launcher does own is assigned from code.

Output is byte-stable: no timestamps, entries sorted, so CI can regenerate and
diff to prove the committed file is current.
"""

from __future__ import annotations

import pathlib
import re
import sys

SOURCE_DIR = pathlib.Path("addons/launcher")
OUT = SOURCE_DIR / "launcher.pot"

# A GDScript double-quoted literal, honouring backslash escapes.
LITERAL = r'"((?:[^"\\]|\\.)*)"'
TR = re.compile(rf"\btr\(\s*{LITERAL}\s*\)")
TR_N = re.compile(rf"\btr_n\(\s*{LITERAL}\s*,\s*{LITERAL}\s*,")
# Two or more format specifiers: a translator who reorders them needs indices.
SPECIFIER = re.compile(r"%(?:\d+\$)?[-+ 0#]*\d*(?:\.\d+)?[sdfxXoc]")

HEADER = '''# Translation template for the launcher's own screens.
#
# Generated by ci/make_pot.py -- do not edit by hand; run the script instead.
#
# A game translates these by adding its own .po files. Put them OUTSIDE
# addons/launcher/ and OUTSIDE ci/ -- res://locale/<lang>.po is the usual home.
# Both of those directories are replaced wholesale by ci/sync_launcher.sh, so a
# .po left inside either one is deleted on the next launcher sync.
#
# Register them in project.godot under
# internationalization/locale/translations, which is a game-owned file and
# survives the sync.
#
msgid ""
msgstr ""
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\\n"
'''


def collect() -> dict[str, dict]:
    entries: dict[str, dict] = {}
    for path in sorted(SOURCE_DIR.glob("*.gd")):
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if line.lstrip().startswith("#"):
                continue
            for match in TR_N.finditer(line):
                single, plural = match.group(1), match.group(2)
                entry = entries.setdefault(single, {"plural": None, "where": []})
                entry["plural"] = plural
                entry["where"].append(f"{path}:{lineno}")
            for match in TR.finditer(line):
                msgid = match.group(1)
                entry = entries.setdefault(msgid, {"plural": None, "where": []})
                entry["where"].append(f"{path}:{lineno}")
    return entries


def render(entries: dict[str, dict]) -> str:
    out = [HEADER]
    for msgid in sorted(entries):
        entry = entries[msgid]
        out.append("")
        for where in entry["where"]:
            out.append(f"#: {where}")
        if len(SPECIFIER.findall(msgid)) > 1:
            # Said explicitly because getting it wrong is a hard runtime error,
            # not a cosmetic one: "build %d · v%s" with the arguments swapped
            # raises "a number is required" and renders the raw format string.
            out.append("#. NOTE: more than one placeholder. To reorder them, use")
            out.append("#. indexed forms (%1$s, %2$d, …). Swapping a bare %s and %d")
            out.append("#. is a runtime error, not a typo.")
        out.append(f'msgid "{msgid}"')
        if entry["plural"] is not None:
            out.append(f'msgid_plural "{entry["plural"]}"')
            out.append('msgstr[0] ""')
            out.append('msgstr[1] ""')
        else:
            out.append('msgstr ""')
    return "\n".join(out) + "\n"


def main() -> int:
    if not SOURCE_DIR.is_dir():
        sys.exit(f"run from the repository root: {SOURCE_DIR} not found")
    entries = collect()
    if not entries:
        sys.exit("no tr() or tr_n() calls found -- refusing to write an empty template")
    text = render(entries)
    check = "--check" in sys.argv
    if check:
        current = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"::error::{OUT} is out of date. Run: python3 ci/make_pot.py", file=sys.stderr)
            return 1
        print(f"{OUT} is up to date ({len(entries)} strings).")
        return 0
    OUT.write_text(text, encoding="utf-8")
    plurals = sum(1 for e in entries.values() if e["plural"] is not None)
    print(f"Wrote {OUT}: {len(entries)} strings ({plurals} with plural forms).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
