#!/usr/bin/env bash
# Stamps this build's identity into the two places that need it before export:
#
#   1. build_version.gd     -- what the running app reports, and what it
#      compares against the manifest to decide whether an update applies.
#   2. export_presets.cfg       -- Android versionCode / versionName.
#
# Both edits are made to the checkout being built and are never committed.
#
# Prints the computed values, and writes them to $GITHUB_OUTPUT when running
# under GitHub Actions.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Artifact names derive from the game's name so a project only states it once.
# They must stay stable across releases: the app fetches them through
# /releases/latest/download/<name>, which only resolves for a fixed name.
# One value per line, because a game name may contain spaces.
mapfile -t _DERIVED < <(python3 - <<'PYEOF'
import json, re

with open("version.json", encoding="utf-8") as fh:
    name = str(json.load(fh).get("game_name", "Game")).strip() or "Game"
slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-") or "game"
exe = re.sub(r"[^A-Za-z0-9]+", "", name) or "Game"
print(name)
print(slug)
print(f"{slug}.apk")
print(f"{exe}.exe")
PYEOF
)
GAME_NAME="${_DERIVED[0]}"
GAME_SLUG="${_DERIVED[1]}"
APK_NAME="${_DERIVED[2]}"
EXE_NAME="${_DERIVED[3]}"

VERSION_NAME="$(python3 -c 'import json;print(json.load(open("version.json",encoding="utf-8"))["version_name"])')"
BINARY_VERSION="$(python3 -c 'import json;print(int(json.load(open("version.json",encoding="utf-8"))["binary_version"]))')"

# Commit count is monotonic on main and moves on every merge, which is exactly
# the property a content version needs.
CONTENT_VERSION="$(git rev-list --count HEAD)"
COMMIT="$(git rev-parse --short=8 HEAD)"
BUILT_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

IS_CI_BUILD=false
if [[ -n "${GITHUB_ACTIONS:-}" ]]; then
	IS_CI_BUILD=true
fi

# This build's own patch notes, baked in so the app can describe itself without
# a network round trip -- offline, or before it has ever checked for updates.
# Written by ci/collect_changes.sh, which must therefore run first.
CHANGES_LITERAL="$(python3 - <<'PY'
import json, os

items = []
path = "build/notes/changes.json"
if os.path.isfile(path):
    try:
        with open(path, encoding="utf-8") as fh:
            items = [str(x) for x in json.load(fh)][:20]
    except (ValueError, OSError):
        items = []
# json.dumps produces string literals GDScript accepts verbatim.
print("[" + ", ".join(json.dumps(i, ensure_ascii=False) for i in items) + "]")
PY
)"

cat > build_version.gd <<EOF
extends RefCounted
## GENERATED BY ci/prepare_build.sh -- do not edit by hand.
##
## The committed copy of this file holds the local-dev defaults (version 0), so
## a build made outside CI always considers itself older than any release and
## will offer to update. CI overwrites it in the workspace immediately before
## exporting, so the shipped APK/EXE and the shipped content pack each carry the
## versions they were actually built with.

## Bumped by hand in version.json. A release advertising a higher value than the
## installed one needs a new APK/EXE -- a content pack cannot deliver it.
const BINARY_VERSION: int = ${BINARY_VERSION}

## Bumped automatically on every release. A higher value alone can be delivered
## as a content pack.
const CONTENT_VERSION: int = ${CONTENT_VERSION}

## Cosmetic, shown in the UI.
const VERSION_NAME: String = "${VERSION_NAME}"

## Short commit SHA this build came from, or "local" outside CI.
const COMMIT: String = "${COMMIT}"

## RFC3339 build timestamp, or "" outside CI.
const BUILT_AT: String = "${BUILT_AT}"

## True when this build came out of CI rather than a local export/editor run.
const IS_CI_BUILD: bool = ${IS_CI_BUILD}

## What landed in this build, newest first. Baked in so the app can show its own
## patch notes with no network access.
const CHANGES := ${CHANGES_LITERAL}
EOF

# Android refuses to install an update whose versionCode is lower than the
# installed one, so versionCode tracks content_version -- which moves on every
# release -- rather than binary_version, which only moves when a new APK is
# genuinely required. Any published APK can therefore install over any older one.
#
# Optional: a project with no export presets yet (or no Android target) still
# gets a valid build stamp, which is all the launcher itself needs.
if [[ -f export_presets.cfg ]]; then
	sed -i -E "s|^version/code=.*|version/code=${CONTENT_VERSION}|" export_presets.cfg
	sed -i -E "s|^version/name=.*|version/name=\"${VERSION_NAME}\"|" export_presets.cfg
else
	echo "No export_presets.cfg; skipping the Android version stamp."
fi

echo "game_name=${GAME_NAME}"
echo "apk_name=${APK_NAME}"
echo "exe_name=${EXE_NAME}"
echo "version_name=${VERSION_NAME}"
echo "binary_version=${BINARY_VERSION}"
echo "content_version=${CONTENT_VERSION}"
echo "commit=${COMMIT}"
echo "built_at=${BUILT_AT}"
echo "tag=v${VERSION_NAME}+${CONTENT_VERSION}"

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
	{
		echo "game_name=${GAME_NAME}"
		echo "game_slug=${GAME_SLUG}"
		echo "apk_name=${APK_NAME}"
		echo "exe_name=${EXE_NAME}"
		echo "version_name=${VERSION_NAME}"
		echo "binary_version=${BINARY_VERSION}"
		echo "content_version=${CONTENT_VERSION}"
		echo "commit=${COMMIT}"
		echo "built_at=${BUILT_AT}"
		echo "tag=v${VERSION_NAME}+${CONTENT_VERSION}"
	} >> "$GITHUB_OUTPUT"
fi
